### ISSUE TITLE
support for Auth0

### ISSUE THREAD

**Issue by johnstonmatt** [scaphold-io/react-apollo-starter-kit#2]
It would be awesome if this project supported auth0.js or Lock out of the box, It's not obvious how to integrate it despite it being a native scaphold integration

**Comment by vning93** [comment]
You can check out our Auth0 Lock playground here. It uses the same GraphQL API that you normally would but actually more generic as it doesn't use Apollo Client.

https://github.com/scaphold-io/auth0-lock-playground
